apiVersion: batch/v1
kind: CronJob
metadata:
  name: google-ping
spec:
  successfulJobsHistoryLimit: 7
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      name: google-ping
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - curl google.com
            image: nginx:1.25.1
            name: google-ping
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'